swagger-api:
  version: "1.0"

server:
  port: 8091
  servlet:
    context-path: /app
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health,info
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ylab_db
    username: postgres
    password: mamaivdybai896712345NIK
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update